In [1]:
testrun = "false"
# testrun = "true"
version = "v1"

In [14]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [3]:
# read in GPT responses
cases_with_gpt = pd.read_csv(f"ebell_outputs/all_cases_gpt4_output_{version}.csv")

In [4]:
# first we duplicate a row that is in multiple data collection forms
# namely, form C, scenario 1 == form A, scenario 1

# before that, we need to name all the other scenarios
cases_with_gpt.loc[0, 'scenarioversion'] = "A"
cases_with_gpt.loc[0, 'scenarionumber'] = 1

cases_with_gpt.loc[1, 'scenarioversion'] = "A"
cases_with_gpt.loc[1, 'scenarionumber'] = 2

cases_with_gpt.loc[2, 'scenarioversion'] = "A"
cases_with_gpt.loc[2, 'scenarionumber'] = 3

cases_with_gpt.loc[3, 'scenarioversion'] = "B"
cases_with_gpt.loc[3, 'scenarionumber'] = 1

cases_with_gpt.loc[4, 'scenarioversion'] = "B"
cases_with_gpt.loc[4, 'scenarionumber'] = 2

cases_with_gpt.loc[5, 'scenarioversion'] = "B"
cases_with_gpt.loc[5, 'scenarionumber'] = 3

cases_with_gpt.loc[6, 'scenarioversion'] = "C"
cases_with_gpt.loc[6, 'scenarionumber'] = 2

cases_with_gpt.loc[7, 'scenarioversion'] = "C"
cases_with_gpt.loc[7, 'scenarionumber'] = 3

In [5]:
# then we duplicate and rename
cases_with_gpt = pd.concat([cases_with_gpt, cases_with_gpt.loc[[0]]], axis=0, ignore_index=True)
cases_with_gpt.loc[8, 'scenarioversion'] = "C"
cases_with_gpt.loc[8, 'scenarionumber'] = 1

In [6]:
cases_with_gpt = cases_with_gpt.sort_values(["scenarioversion", "scenarionumber"])

In [7]:
cases_with_gpt['scenarioID'] = cases_with_gpt["scenarioversion"] +  cases_with_gpt["scenarionumber"].astype(int).astype(str)

In [8]:
cases_with_gpt.head(5)

,note_id,scenario,probability_q,management_q,valupdate_management_q,management_option_1,management_option_2,management_option_3,true_pretest,pretest_prob,management_decision,true_prob_management_decision,pretest_llm_output,management_decision_llm_output,true_prob_management_decision_llm_output,scenarioversion,scenarionumber,scenarioID
0,1,A patient presents with a 3 day history of cou...,The probability of community acquired pneumoni...,"Based on this probability, you choose the foll...",Based on a validated clinical decision rule th...,"You feel that CAP is adequately ruled out, no ...",You order an CXR to evaluate for possible CAP,You feel that CAP is likely enough to prescrib...,2,10.0,"You feel that CAP is adequately ruled out, no ...","You feel that CAP is adequately ruled out, no ...",To estimate the probability of community-acqui...,Given the low likelihood of CAP based on the c...,With the additional information that a validat...,A,1.0,A1
1,2,A patient presents with a 3 day history of cou...,The probability of community acquired pneumoni...,"Based on this probability, you choose the foll...",Based on a validated clinical decision rule th...,"You feel that CAP is adequately ruled out, no ...",You order an CXR to evaluate for possible CAP,You feel that CAP is likely enough to prescrib...,17,60.0,You order an CXR to evaluate for possible CAP,"You feel that CAP is adequately ruled out, no ...",To estimate the likelihood of community-acquir...,Given the probability estimate of 60% for the ...,With a revised probability of 17% for communit...,A,2.0,A2
2,3,A patient presents with a 3 day history of cou...,The probability of community acquired pneumoni...,"Based on this probability, you choose the foll...",Based on a validated clinical decision rule th...,"You feel that CAP is adequately ruled out, no ...",You order an CXR to evaluate for possible CAP,You feel that CAP is likely enough to prescrib...,45,70.0,You order an CXR to evaluate for possible CAP,You order an CXR to evaluate for possible CAP,To estimate the likelihood that this patient h...,"Given the estimated probability of CAP at 70%,...",With a revised likelihood of CAP at 45% based ...,A,3.0,A3
3,4,A patient presents with a 3 day history of cou...,The probability of community acquired pneumoni...,"Based on this probability, you choose the foll...",Based on a validated clinical decision rule th...,"You feel that CAP is adequately ruled out, no ...",You order an CXR to evaluate for possible CAP,You feel that CAP is likely enough to prescrib...,5,30.0,You order an CXR to evaluate for possible CAP,"You feel that CAP is adequately ruled out, no ...",To estimate the probability of community-acqui...,Given the probability estimate of 30% for comm...,"With a revised probability of 5%, the likeliho...",B,1.0,B1
4,5,A patient presents with a 3 day history of cou...,The probability of community acquired pneumoni...,"Based on this probability, you choose the foll...",Based on a validated clinical decision rule th...,"You feel that CAP is adequately ruled out, no ...",You order an CXR to evaluate for possible CAP,You feel that CAP is likely enough to prescrib...,24,70.0,You order an CXR to evaluate for possible CAP,You order an CXR to evaluate for possible CAP,To estimate the likelihood of community-acquir...,Given the probability estimate of 70% for comm...,With a revised probability of 24% for communit...,B,2.0,B2

In [9]:
with pd.option_context("display.max_colwidth", None):
    display(cases_with_gpt[['scenario', "valupdate_management_q"]])

,scenario,valupdate_management_q
0,"A patient presents with a 3 day history of cough productive of yellowish green sputum and a runny nose. He is afebrile, his heart rate is 72 bpm, and his lung sounds are normal.","Based on a validated clinical decision rule that uses, signs, symptoms, and CRP, the patient’s likelihood of CAP is actually 2%. Based on that revised probability, what is your decision:"
1,"A patient presents with a 3 day history of cough productive of yellowish green sputum and a runny nose. He is not short of breath, his measured temp is 100.6 F, his heart rate is 80 bpm, and his lung exam reveals crackles.","Based on a validated clinical decision rule that uses, signs, symptoms, and CRP, the patient’s likelihood of CAP is actually 17%. Based on that revised probability, what is your decision:"
2,"A patient presents with a 3 day history of cough productive of yellowish green sputum and he has a runny nose. He is somewhat short of breath. His measured temp is 101.0 F, his heart rate is 104 bpm, and his lung exam reveals crackles.","Based on a validated clinical decision rule that uses, signs, symptoms, and CRP, the patient’s likelihood of CAP is actually 45%. Based on that revised probability, what is your decision:"
3,"A patient presents with a 3 day history of cough productive of yellowish green sputum and a runny nose. He has a measured temperature of 38.4 C (101.1 F), his heart rate is 72 bpm, and his lung sounds are normal.","Based on a validated clinical decision rule that uses, signs, symptoms, and CRP, the patient’s likelihood of CAP is actually 5%. Based on that revised probability, what is your decision:"
4,"A patient presents with a 3 day history of cough productive of yellowish green sputum and a runny nose. He is somewhat short of breath, his measured temp is 101.2 F, his heart rate is 80 bpm, and his lung exam reveals crackles.","Based on a validated clinical decision rule that uses, signs, symptoms, and CRP, the patient’s likelihood of CAP is actually 24%. Based on that revised probability, what is your decision:"
5,"A patient presents with a 3 day history of cough productive of yellowish green sputum. He denies having a runny nose. He is somewhat short of breath. His measured temp is 101.4 F, his heart rate is 106 bpm, and his lung exam reveals crackles.","Based on a validated clinical decision rule that uses, signs, symptoms, and CRP, the patient’s likelihood of CAP is actually 62%. Based on that revised probability, what is your decision:"
8,"A patient presents with a 3 day history of cough productive of yellowish green sputum and a runny nose. He is afebrile, his heart rate is 72 bpm, and his lung sounds are normal.","Based on a validated clinical decision rule that uses, signs, symptoms, and CRP, the patient’s likelihood of CAP is actually 2%. Based on that revised probability, what is your decision:"
6,"A patient presents with a 3 day history of cough productive of yellowish green sputum. He denies having a runny nose, but is somewhat short of breath. He is afebrile, his heart rate is 80 bpm, and his lung exam reveals crackles.","Based on a validated clinical decision rule that uses, signs, symptoms, and CRP, the patient’s likelihood of CAP is actually 11%. Based on that revised probability, what is your decision:"
7,"A patient presents with a 3 day history of cough productive of yellowish green sputum. He denies having a runny nose. He is somewhat short of breath. His measured temp is 100.8 F, his heart rate is 84 bpm, and his lung exam reveals crackles.","Based on a validated clinical decision rule that uses, signs, symptoms, and CRP, the patient’s likelihood of CAP is actually 39%. Based on that revised probability, what is your decision:"

In [10]:
# read in physician estimates
physician_data = pd.read_stata("~/project/Uncertainty_data/Ebell_data/ThresholdCoughFinal.dta")

In [11]:
physician_data['scenarioID'] = physician_data["scenarioversion"] + physician_data["scenarionumber"].astype(int).astype(str)

In [12]:
physician_data

,id,site,scenarioversion,yearspractice,practicesite,cxrproximity,scenarionumber,scenariopercent,scenariocategory,scenariorevised,PercentPneumonia,scenarioID
0,1,Chicago,C,29.0,1,1,1,2.0,A,A,2.0,C1
1,1,Chicago,C,29.0,1,1,2,80.0,B,B,11.0,C2
2,1,Chicago,C,29.0,1,1,3,87.0,B,B,39.0,C3
3,2,Chicago,B,1.5,1,1,1,5.0,A,A,5.0,B1
4,2,Chicago,B,1.5,1,1,2,15.0,B,B,24.0,B2
...,...,...,...,...,...,...,...,...,...,...,...,...
763,255,Lausanne,C,25.0,1,1,2,12.5,B,Z,11.0,C2
764,255,Lausanne,C,25.0,1,1,3,70.0,C,Z,39.0,C3
765,256,Lausanne,B,1.0,3,1,1,10.0,A,A,5.0,B1
766,256,Lausanne,B,1.0,3,1,2,60.0,B,B,24.0,B2
767,256,Lausanne,B,1.0,3,1,3,90.0,C,B,62.0,B3

In [ ]:
# thresholds for low, medium, and high risks of CAP based on validated risk score
# low (probability <2.5%), intermediate (2.5-20%), and high (>20%)

We want two data points from this study

1. The percentage difference from estimation to true, betweeen the physicians and the LLMs.
    1. The first one will be lumped into the pre-test data comparison with risk-score calculators data I get from Thomas/Don
2. We will figure out how many people changed their decisions for low, medium, and high CAP-risk groups, for both the LLMs and the physicians

In [49]:
# for (2), we first need to split up the physician data into risk groups
def add_CAP_risk_levels(df, pretest_prob_colname, true_prob_colname):
    # for (2), we first need to split up the physician data into risk groups
    df["true_risk"] = np.where(df[true_prob_colname] < 2.5, "low", np.nan)
    df["true_risk"] = np.where((df[true_prob_colname] >= 2.5) & (df[true_prob_colname] <= 20) , "medium", df["true_risk"])
    df["true_risk"] = np.where((df[true_prob_colname] > 20), "high", df["true_risk"])    
    
    df["estimate_risk"] = np.where(df[pretest_prob_colname] < 2.5, "low", np.nan)
    df["estimate_risk"] = np.where((df[pretest_prob_colname] >= 2.5) & (df[pretest_prob_colname] <= 20) , "medium", df["estimate_risk"])
    df["estimate_risk"] = np.where((df[pretest_prob_colname] > 20), "high", df["estimate_risk"])

    return df 
    
physician_data = add_CAP_risk_levels(physician_data, "scenariopercent", "PercentPneumonia")

In [50]:
physician_data["true_risk"].value_counts(), physician_data["estimate_risk"].value_counts()

(true_risk
 high      355
 medium    256
 low       157
 Name: count, dtype: int64,
 estimate_risk
 high      464
 medium    268
 low        36
 Name: count, dtype: int64)

There's a number of situations that can occur for (2). 

- Initial estimate and true prob could be in different risk categories, and then the individual changes their decision.
- Initial estimate and true prob could be in different risk categories, and the individual keeps their decision. 
- Initial estimate and true prob could be in same risk categories, and the individual changes their decision.
- Initial estimate and true prob could be in same risk categories, and the individual keeps their decision.

*The question we want to answer is, when the true probability is in a different risk group to the estimated probability, what does the LLM do? How about the physician? How do they differ?*

In [78]:
# let's try one
different_risks = physician_data[physician_data['true_risk'] != physician_data['estimate_risk']]

In [79]:
# ask what AB, BC, and Z are, but for now, drop em. 
display(different_risks["scenariocategory"].value_counts(), different_risks["scenariorevised"].value_counts())

different_risks = different_risks[(different_risks['scenariocategory'].isin(['A', "B", "C"])) &
                (different_risks['scenariorevised'].isin(['A', "B", "C"]))]

scenariocategory
A     158
B     108
C      24
AB      1
BC      1
Name: count, dtype: int64

scenariorevised
A    185
B     89
C     12
Z      6
Name: count, dtype: int64

In [83]:
different_risks_low = different_risks[different_risks['true_risk'] == "low"]
different_risks_medium = different_risks[different_risks['true_risk'] == "medium"]
different_risks_high = different_risks[different_risks['true_risk'] == "high"]

In [84]:
different_risks_counts = different_risks[['scenariocategory', "scenariorevised"]].value_counts(normalize=True).sort_index()

In [85]:
display(different_risks_counts)
different_risks_counts.loc[('A', "A")] + different_risks_counts.loc[('B', "B")] + different_risks_counts.loc[('C', "C")]

scenariocategory  scenariorevised
A                 A                  0.524648
                  B                  0.014085
                  C                  0.003521
B                 A                  0.102113
                  B                  0.267606
                  C                  0.010563
C                 A                  0.024648
                  B                  0.024648
                  C                  0.028169
Name: proportion, dtype: float64

0.8204225352112675

In [86]:
# look at it by risk group: 
display(different_risks_low[['scenariocategory', "scenariorevised"]].value_counts(normalize=True).sort_index())
display(different_risks_medium[['scenariocategory', "scenariorevised"]].value_counts(normalize=True).sort_index())
display(different_risks_high[['scenariocategory', "scenariorevised"]].value_counts(normalize=True).sort_index())

scenariocategory  scenariorevised
A                 A                  0.984375
                  B                  0.007812
B                 A                  0.007812
Name: proportion, dtype: float64

scenariocategory  scenariorevised
A                 A                  0.150376
                  B                  0.007519
B                 A                  0.203008
                  B                  0.503759
                  C                  0.007519
C                 A                  0.052632
                  B                  0.045113
                  C                  0.030075
Name: proportion, dtype: float64

scenariocategory  scenariorevised
A                 A                  0.130435
                  B                  0.086957
                  C                  0.043478
B                 A                  0.043478
                  B                  0.391304
                  C                  0.086957
C                 B                  0.043478
                  C                  0.173913
Name: proportion, dtype: float64

In [108]:
different_risks_medium_BtoA = different_risks_medium[(different_risks_medium['scenariocategory'] == "B") & (different_risks_medium['scenariorevised'] == "A")]
(different_risks_medium_BtoA["scenariopercent"] - different_risks_medium_BtoA["PercentPneumonia"]).describe()
# we see here that in all cases where the decision went from treat to rule-out, the initial estimate was much higher.

count    27.000000
mean     29.111111
std      11.486894
min       8.000000
25%      19.500000
50%      25.000000
75%      37.000000
max      64.000000
dtype: float64

In [62]:
choice_map = {"A": "You feel that CAP is adequately ruled out, no CXR is needed",
"B": "You order an CXR to evaluate for possible CAP",
"C": "You feel that CAP is likely enough to prescribe an antibiotic without a CXR"}

In [63]:
# do the same with the GPT model
cases_with_gpt = add_CAP_risk_levels(cases_with_gpt, "pretest_prob", "true_pretest")

In [91]:
different_risks_gpt = cases_with_gpt[cases_with_gpt['true_risk'] != cases_with_gpt['estimate_risk']]
different_risks_gpt_low = different_risks_gpt[different_risks_gpt['true_risk'] == "low"]
different_risks_gpt_medium = different_risks_gpt[different_risks_gpt['true_risk'] == "medium"]
different_risks_gpt_high = different_risks_gpt[different_risks_gpt['true_risk'] == "high"]

In [65]:
different_risks_gpt[['management_decision', "true_prob_management_decision"]].value_counts(normalize=True).sort_index()

management_decision                                          true_prob_management_decision
You feel that CAP is adequately ruled out, no CXR is needed  You feel that CAP is adequately ruled out, no CXR is needed    0.4
You order an CXR to evaluate for possible CAP                You feel that CAP is adequately ruled out, no CXR is needed    0.4
                                                             You order an CXR to evaluate for possible CAP                  0.2
Name: proportion, dtype: float64

In [93]:
# look at it by risk group for GPT model: 
display(different_risks_gpt_low[['management_decision', "true_prob_management_decision"]].value_counts(normalize=True).sort_index())
print("\n=====================\n")
display(different_risks_gpt_medium[['management_decision', "true_prob_management_decision"]].value_counts(normalize=True).sort_index())
print("\n=====================\n")
display(different_risks_gpt_high[['management_decision', "true_prob_management_decision"]].value_counts(normalize=True).sort_index())

management_decision                                          true_prob_management_decision
You feel that CAP is adequately ruled out, no CXR is needed  You feel that CAP is adequately ruled out, no CXR is needed    1.0
Name: proportion, dtype: float64

=====================

management_decision                            true_prob_management_decision
You order an CXR to evaluate for possible CAP  You feel that CAP is adequately ruled out, no CXR is needed    0.666667
                                               You order an CXR to evaluate for possible CAP                  0.333333
Name: proportion, dtype: float64

=====================

Series([], Name: proportion, dtype: float64)

In [103]:
different_risks_gpt_medium_BtoA = different_risks_gpt_medium[(different_risks_gpt_medium['management_decision'] == "You order an CXR to evaluate for possible CAP") & 
(different_risks_gpt_medium['true_prob_management_decision'] == "You feel that CAP is adequately ruled out, no CXR is needed")]

In [105]:
(different_risks_gpt_medium_BtoA['pretest_prob'] - different_risks_gpt_medium_BtoA['true_pretest']).describe()

count     2.000000
mean     34.000000
std      12.727922
min      25.000000
25%      29.500000
50%      34.000000
75%      38.500000
max      43.000000
dtype: float64